version: 0.2

phases:
  install:
    commands:
      - npm ci

  build:
    commands:
      - npm run build        # Gera .next
      - npm run export       # Gera a pasta out/

  post_build:
    commands:
      - aws s3 sync out/ s3://autowebspec.com.br --delete
      - aws cloudfront create-invalidation --distribution-id E37VMDJJ880GJR --paths "/*"

artifacts:
  files:
    - '**/*'
