version: 0.3

env:
  variables:
    NEXT_PUBLIC_BASE_URL_CARS: "https://sq6vim0sm9.execute-api.us-east-1.amazonaws.com/dev"
    NEXT_PUBLIC_BASE_URL_NEWS: "https://j7haei5ftd.execute-api.us-east-1.amazonaws.com/dev"

phases:
  install:
    commands:
      - echo "Instalando dependências..."
      - npm ci

  build:
    commands:
      - echo "Rodando build Next.js..."
      - npm run build
      - npm run export

  post_build:
    commands:
      - echo "Sincronizando com S3..."
      - aws s3 sync out/ s3://autowebspec.com.br --delete
      - echo "Criando invalidação no CloudFront..."
      - aws cloudfront create-invalidation --distribution-id E37VMDJJ880GJR --paths "/*"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/*         # cache das dependências do Node
    - .next/cache/**/*          # cache do build Next.js
