version: 0.2

env:
  variables:
    NEXT_PUBLIC_BASE_URL_CARS: "https://sq6vim0sm9.execute-api.us-east-1.amazonaws.com/dev"
    NEXT_PUBLIC_BASE_URL_NEWS: "https://j7haei5ftd.execute-api.us-east-1.amazonaws.com/dev"

phases:
  install:
    commands:
      - npm ci

  build:
  commands:
    - echo "NEXT_PUBLIC_BASE_URL_CARS=$NEXT_PUBLIC_BASE_URL_CARS" >> .env
    - echo "NEXT_PUBLIC_BASE_URL_NEWS=$NEXT_PUBLIC_BASE_URL_NEWS" >> .env
    - echo "NEXT_PUBLIC_GOOGLE_TAG=$NEXT_PUBLIC_GOOGLE_TAG" >> .env
    - npm run build


  post_build:
    commands:
      - aws s3 sync out/ s3://autowebspec.com.br --delete
      - aws cloudfront create-invalidation --distribution-id E37VMDJJ880GJR --paths "/*"

artifacts:
  files:
    - '**/*'
